@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR
skinparam classBackgroundColor UI_COLOR

Package EventUI <<Rectangle>>{
Class EventListPanel
Class EventCard
}

Package Model {}

Class HiddenOutside #FFFFFF
HiddenOutside ..> EventListPanel

EventListPanel --> "*" EventCard

EventCard ..> Model
@enduml
