@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

package Person {
Class UniquePersonList
Class Person
Class Email
Class Name
Class Phone
Class Tag
Class Telegram
}

package Event {
Class UniqueEventList
Class Event
Class EventName
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
AddressBook *-down--> "1" UniqueEventList
UniquePersonList --> "~* all" Person
UniqueEventList -down-> "~* all" Event
Person *--> "1" Name
Person *--> "0..1" Phone
Person *--> "0..1" Email
Person *--> "0..1" Telegram
Person *--> "*" Tag
Event *-down-> EventName
Event -right-> "attendees" UniquePersonList

Name -[hidden]right-> Phone

ModelManager -->"~* filtered" Person
ModelManager --> Event
@enduml
